name: Release

on:
  push:
    tag:
    - v*

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 15
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build app for release
        if: runner.os == 'Windows'
        run: msbuild Windows\reaper_csurf_integrator\reaper_csurf_integrator\reaper_csurf_integrator.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Archive production artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: reaper_csurf_integrator-windows
          path: D:\a\csi-reasonus\csi-reasonus\Windows\reaper_csurf_integrator\reaper_csurf_integrator\Release\reaper_csurf_integrator.dll
          if-no-files-found: error

      - name: "Select Xcode 13.2"
        if: runner.os == 'MacOs'
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "13.2"

      - name: "Build"
        if: runner.os == 'MacOs'
        uses: devbotsxyz/xcode-build@v1

      - name: Package for Distribution
        if: runner.os == 'MacOs'
        run: ditto -V -c -k  "/Users/runner/Export/reaper_csurf_integrator.dylib" "reaper_csurf_integrator.zip"

      - name: Archive production artifacts
        if: runner.os == 'MacOs'
        uses: actions/upload-artifact@v3
        with:
          name: reaper_csurf_integrator-macos
          path: reaper_csurf_integrator.zip
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            **/*reaper_csurf_integrator-*.zip
