name: Release

on:
  push:
    tag:
    - v*

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    # runs-on: macos-latest
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[15.0)'
          msbuild-architecture: x64

      - name: Build app for release
        run: msbuild Windows\reaper_csurf_integrator\reaper_csurf_integrator\reaper_csurf_integrator.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

      # - name: "Select Xcode 13.2"
      #   uses: devbotsxyz/xcode-select@v1
      #   with:
      #     version: "13.2"

      # - name: "Build"
      #   uses: devbotsxyz/xcode-build@v1

      # - name: Package for Distribution
      #   run: ditto -V -c -k  "/Users/runner/Export/reaper_csurf_integrator.dylib" "reaper_csurf_integrator.zip"

      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: reaper_csurf_integrator
      #     path: reaper_csurf_integrator.zip
      #     if-no-files-found: error

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     draft: true
      #     files: |
      #       reaper_csurf_integrator.zip
